INSERT INTO USERS (FIRST_NAME, LAST_NAME, AGE)
  VALUES ('Maksim', 'Loyan', 21);

INSERT INTO PRODUCTS (NAME, PRICE, CATEGORY, GENDER, COLOUR, "SIZE", QUANTITY)
  VALUE ('NIKE', 20, 'T-shorts', 'Man', 'yellow', 'L', 10);
