INSERT INTO USERS (FIRST_NAME, LAST_NAME, AGE)
  VALUES ('John', 'Travolta', 33);
INSERT INTO USERS (FIRST_NAME, LAST_NAME, AGE)
  VALUES ('Vasya', 'Pupkin', 44);
INSERT INTO USERS (FIRST_NAME, LAST_NAME, AGE)
  VALUES ('Alice', 'Doe', 55);
INSERT INTO USERS (FIRST_NAME, LAST_NAME, AGE)
  VALUES ('Valera', 'Popovets', 22);
INSERT INTO USERS (FIRST_NAME, LAST_NAME, AGE)
  VALUES ('Jeck', 'Vorobey', 11);
INSERT INTO USERS (FIRST_NAME, LAST_NAME, AGE)
  VALUES ('Ivan', 'Ivanov', 34);
